name: inm_6
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  elegant_notification: ^1.10.0
  provider: ^6.0.0
  intl: any
  flutter_form_builder: ^9.0.0
  form_builder_validators: ^9.0.0
  desktop_window: ^0.4.0
  alphabet_scroll_view: ^0.3.2
  mongo_dart: ^0.9.1
  window_manager: ^0.3.4
  mysql_client: ^0.0.27
  path: ^1.8.3
  flutter_phoenix: ^1.1.1

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
